/**
 * Cost tracking for OpenAI image generation calls.
 *
 * Pricing is not exposed by the API itself, so per-image costs are held in a
 * small lookup table below (USD, as published by OpenAI at the time this was
 * written). If OpenAI changes pricing or a new model/size combination is
 * used, `estimateImageCostUsd` falls back to the most expensive known price
 * for that model so tracking stays conservative rather than silently
 * under-counting spend. Update the table when pricing changes.
 */

// price per image, in USD, keyed by "<quality>:<size>"
const DALLE_PRICING_USD: Record<string, Record<string, number>> = {
  'dall-e-3': {
    'standard:1024x1024': 0.04,
    'standard:1024x1792': 0.08,
    'standard:1792x1024': 0.08,
    'hd:1024x1024': 0.08,
    'hd:1024x1792': 0.12,
    'hd:1792x1024': 0.12,
  },
  'dall-e-2': {
    'standard:256x256': 0.016,
    'standard:512x512': 0.018,
    'standard:1024x1024': 0.02,
  },
};

const DEFAULT_PRICE_USD = 0.04;

/** Estimated price of a single generated image, in USD. */
export function estimateImageCostUsd(model: string, size: string, quality = 'standard'): number {
  const modelPricing = DALLE_PRICING_USD[model];
  if (!modelPricing) {
    return DEFAULT_PRICE_USD;
  }
  const exact = modelPricing[`${quality}:${size}`];
  if (exact !== undefined) {
    return exact;
  }
  // Unknown size/quality for a known model: fall back to the most expensive
  // known price for that model rather than guessing low.
  return Math.max(...Object.values(modelPricing));
}

export interface ImageGenerationUsage {
  model: string;
  size: string;
  quality?: string;
  /** Number of images generated by this call. */
  count: number;
  /** Total estimated cost of this call, in USD (per-image price * count). */
  costUsd: number;
  timestamp: number;
}

/**
 * Accumulates estimated spend across image generation calls for the life of
 * the process. In-memory only; sufficient for the alerting/soft-budget use
 * case this task asks for. A persistent ledger (e.g. a database table) can
 * be layered on later if we need cost history across restarts.
 */
export class CostTracker {
  private usage: ImageGenerationUsage[] = [];

  record(
    model: string,
    size: string,
    quality: string | undefined,
    count: number,
    timestamp: number = Date.now()
  ): ImageGenerationUsage {
    const perImage = estimateImageCostUsd(model, size, quality);
    const entry: ImageGenerationUsage = {
      model,
      size,
      quality,
      count,
      costUsd: perImage * count,
      timestamp,
    };
    this.usage.push(entry);
    return entry;
  }

  get totalCostUsd(): number {
    return this.usage.reduce((sum, u) => sum + u.costUsd, 0);
  }

  get totalImages(): number {
    return this.usage.reduce((sum, u) => sum + u.count, 0);
  }

  /** Read-only history of every recorded generation call, oldest first. */
  get history(): readonly ImageGenerationUsage[] {
    return this.usage;
  }

  reset(): void {
    this.usage = [];
  }
}
