-- Migration: 0005_create_gifs_table
-- Purpose: the core catalog table -- one row per GIF shown in the gallery,
--   regardless of where it came from (pulled from Giphy/Tenor, generated by
--   AI, converted from an uploaded image, or uploaded directly).
--
-- Design notes:
--   * `source` is a coarse enum for filtering/reporting ("show me all
--     AI-generated gifs"). Anything specific to a third-party provider
--     (external id, external url, attribution, raw API payload) lives in
--     `third_party_references` (0007), which a gif can have zero, one or
--     more of -- e.g. an AI-generated gif might reference the source image
--     it was converted from *and* the model/provider that generated it.
--   * `metadata` is JSONB for provider- or pipeline-specific fields we don't
--     want to keep adding columns for (e.g. generation prompt, palette,
--     frame_count). Frequently-filtered/sorted attributes that we already
--     know about (dimensions, size, duration, mime type) get real columns
--     instead, so they stay indexable and typed.
--   * Soft delete via `deleted_at` + `status` so gifs can be hidden/undone
--     without losing history; see docs/database-schema.md for the
--     retention/purge strategy.
--   * `search_vector` is a generated (STORED) column, kept in sync by
--     Postgres itself on every INSERT/UPDATE -- no application code or
--     trigger required, and it is indexed with GIN for full-text search on
--     title + description.
--
-- Locking behaviour: brand-new table, no contention. The two enum types are
--   created first as a separate, near-instant catalog change.
-- Rollback: 0005_create_gifs_table.down.sql drops the table and the two enum
--   types. Safe as long as gif_tags/third_party_references (which reference
--   gifs.id) have already been rolled back -- enforced by running
--   `migrate down` in reverse order.
-- Data impact: none, creates an empty table.

CREATE TYPE gif_source AS ENUM ('giphy', 'tenor', 'upload', 'ai_generated', 'other');
CREATE TYPE gif_status AS ENUM ('active', 'archived', 'flagged', 'deleted');

CREATE TABLE gifs (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  source           gif_source NOT NULL,
  title            VARCHAR(255) NOT NULL,
  description      TEXT,
  category_id      UUID REFERENCES categories(id) ON DELETE SET NULL,

  url              TEXT NOT NULL,
  thumbnail_url    TEXT,
  storage_path     TEXT,

  width            INTEGER CHECK (width > 0),
  height           INTEGER CHECK (height > 0),
  file_size_bytes  BIGINT CHECK (file_size_bytes >= 0),
  duration_ms      INTEGER CHECK (duration_ms >= 0),
  mime_type        VARCHAR(100) NOT NULL DEFAULT 'image/gif',

  metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
  status           gif_status NOT NULL DEFAULT 'active',

  search_vector    TSVECTOR GENERATED ALWAYS AS (
                      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                      setweight(to_tsvector('english', coalesce(description, '')), 'B')
                    ) STORED,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ,

  CONSTRAINT gifs_title_not_blank CHECK (btrim(title) <> ''),
  CONSTRAINT gifs_url_not_blank CHECK (btrim(url) <> ''),
  CONSTRAINT gifs_metadata_is_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT gifs_deleted_at_matches_status CHECK (
    (status = 'deleted' AND deleted_at IS NOT NULL) OR
    (status <> 'deleted' AND deleted_at IS NULL)
  )
);

-- Listing/browsing: category filter, newest-first pagination.
CREATE INDEX gifs_category_id_idx ON gifs (category_id);
CREATE INDEX gifs_created_at_idx ON gifs (created_at DESC);
CREATE INDEX gifs_source_idx ON gifs (source);

-- Fast "active gifs" filtering without scanning archived/deleted rows.
CREATE INDEX gifs_active_created_at_idx ON gifs (created_at DESC) WHERE status = 'active';

-- Full-text search over title/description.
CREATE INDEX gifs_search_vector_idx ON gifs USING GIN (search_vector);

-- Ad-hoc querying of provider-specific/pipeline metadata (e.g. metadata @> '{"model": "dall-e-3"}').
CREATE INDEX gifs_metadata_idx ON gifs USING GIN (metadata jsonb_path_ops);

CREATE TRIGGER gifs_set_updated_at
  BEFORE UPDATE ON gifs
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
