-- Migration: 0007_create_third_party_references_table
-- Purpose: provenance for a gif -- where its content actually came from.
--   A gif can have zero (a plain local upload with no external origin),
--   one (pulled from Giphy/Tenor, or generated by an AI provider) or more
--   references (e.g. an AI-generated gif that also records the uploaded
--   source image it was converted from). Kept separate from `gifs` so the
--   catalog table stays provider-agnostic and this table can carry the raw
--   API payload for audit/debugging without bloating every gif row.
--
-- Locking behaviour: brand-new table with one FK to gifs; no contention on
--   a fresh database. Same reasoning as 0006 for an existing cluster.
-- Rollback: drops the table and the provider enum. Safe at any time --
--   nothing references this table.
-- Data impact: none, creates an empty table.

CREATE TYPE third_party_provider AS ENUM ('giphy', 'tenor', 'openai', 'user_upload', 'other');

CREATE TABLE third_party_references (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gif_id        UUID NOT NULL REFERENCES gifs(id) ON DELETE CASCADE,

  provider      third_party_provider NOT NULL,
  external_id   TEXT,
  external_url  TEXT,
  attribution   TEXT,
  license       VARCHAR(100),
  raw_metadata  JSONB NOT NULL DEFAULT '{}'::jsonb,

  fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT third_party_references_raw_metadata_is_object
    CHECK (jsonb_typeof(raw_metadata) = 'object')
);

CREATE INDEX third_party_references_gif_id_idx ON third_party_references (gif_id);
CREATE INDEX third_party_references_provider_idx ON third_party_references (provider);

-- Prevent importing the same third-party asset twice (e.g. re-pulling the
-- same Giphy id). NULL external_id (nothing to dedupe on) is allowed to
-- repeat freely, hence the partial index.
CREATE UNIQUE INDEX third_party_references_provider_external_id_unique_idx
  ON third_party_references (provider, external_id)
  WHERE external_id IS NOT NULL;
